### ISSUE TITLE
`drain` and `zrest` modules not included by default

### ISSUE THREAD

**Issue by GingerAdonis** [wireapp/restund#5]
Both the `drain` and `zrest` modules are not included for compilation by default. Is there a reason for this?

**Comment by jschaul** [comment]
`restund` code is owned by http://www.creytiv.com/restund.html - this repo started as a mirror, which has become a little bit of a fork.

The version we use at Wire is built from [here](https://github.com/wireapp/wire-server/blob/develop/services/restund/) and [includes those two modules by default](https://github.com/wireapp/wire-server/blob/develop/services/restund/Makefile#L18). Perhaps the code could be organized differently. As creytiv doesn't have an upstream source repository that makes it easy to send a PR or patch and get a new release, the process around this is not ideal.

Thanks for your PRs, they look useful (review/merge may take a little time though, April is a little busy for us)

**Comment by GingerAdonis** [comment]
Ah of course. I somehow assumed the files were included in this project. Thanks for the reply. :)

Edit: They actually are in this project. Just not enabled like you said. All good.
